# This file definds collision spheres of the arm as per RelaxedIK (https://graphics.cs.wisc.edu/Papers/2018/RMG18a/p43.pdf)
robot: 'ur16e'
collision_spheres:
    shoulder_link:
        - "center": [0.0, 0.0, 0.0] #x, y, z
          "radius": 0.05
    upper_arm_link:
        - "center": [-0.02, 0.0, 0.18]
          "radius": 0.11 #0.5
        # - "center": [-0.15, 0.0, 0.18]
        #   "radius": 0.06 #0.5
        - "center": [-0.2, 0.0, 0.18]
          "radius": 0.06 #0.5
        - "center": [-0.33, 0.0, 0.18]
          "radius": 0.06 #0.5
        - "center": [-0.47, 0.0, 0.18]
          "radius": 0.075 #0.5
    forearm_link:
        - "center": [0.0, 0.0, 0.04]
          "radius": 0.05 #0.4
        # - "center": [-0.06, 0.0, 0.04]
        #   "radius": 0.06 #0.4
        - "center": [-0.11, 0.0, 0.04]
          "radius": 0.05 #0.4
        # - "center": [-0.2, 0.0, 0.04]
        #   "radius": 0.05 #0.5
        - "center": [-0.22, 0.0, 0.04]
          "radius": 0.05 #0.5
        - "center": [-0.35, 0.0, 0.04]
          "radius": 0.07 #0.5
    wrist_1_link:
        - "center": [0.0, 0.01, 0.0]
          "radius": 0.055
    wrist_2_link:
        - "center": [-0.0, -0.01, -0.01]
          "radius": 0.055
    # wrist_3_link:
    #     - "center": [0.0, 0.0924, 0.0031]
    #       "radius": 0.05 #0.0549
    wrist_3_link:
        - "center": [0.0, 0.0, -0.03]
          "radius": 0.035 #0.06 #0.0351
        # gripper lays flat pointing forward on y-axis
        # base link
        - "center": [0.0, 0.0, 0.05]
          "radius": 0.0425
        # # right bar
        - "center": [0.068, 0.03, 0.09]
          "radius": 0.01
        - "center": [0.047, 0.03, 0.05]
          "radius": 0.01
        # left bar - opposite
        - "center": [-0.068, -0.03, 0.09]
          "radius": 0.01
        - "center": [-0.047, -0.03, 0.05]
          "radius": 0.01
        # # right distal phalanx
        # - "center": [0.0515, 0.2465, 0.0031]
        #   "radius": 0.0112
        - "center": [-0.045, -0.02, 0.135]
          "radius": 0.01 #0.0052
        # left distal phalanx - opposite
        # - "center": [-0.0515, 0.2465, 0.0031]
        #   "radius": 0.05 #0.0112
        - "center": [0.045, 0.02, 0.135]
          "radius": 0.01 #0.0052
